[theme]
primaryColor = "#0070F2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F6F7"
textColor = "#1D2D3E"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
